import { expect, test, type Page } from '@playwright/test'

const phones = (page: Page) => page.getByTestId('gallery-page')
const destination = (page: Page) => page.getByRole('combobox', { name: 'Navigate to', exact: true })
async function folio(page: Page) {
  await page.setViewportSize({ width: 1920, height: 1200 })
  await page.goto('/')
  await page.getByTestId('gallery-source-app').click()
  await page.getByTestId('template-folio').click()
  await page.getByTestId('template-confirm').click()
  await expect(page.getByTestId('render-tree').getByText('The Secret Garden', { exact: true })).toBeVisible()
  await page.getByTestId('inspect-toggle').click()
  await expect(phones(page)).toHaveCount(3)
  await page.getByTestId('logical-layers').getByRole('treeitem', { name: 'Book row, Component', exact: true }).click()
  await expect(destination(page)).toBeVisible()
  await expect(page.getByTestId('navigation-destination-editor')).toContainText('book')
}
test('canvas eyedropper cancels safely, preserves selection, and applies the chosen tab screen', async ({ page }, testInfo) => {
  await folio(page)
  const original = await destination(page).inputValue()
  const library = phones(page).filter({ has: page.getByRole('button', { name: 'Edit Library', exact: true }) })
  const originalBounds = await library.boundingBox()
  await page.getByRole('button', { name: 'Pick screen from canvas', exact: true }).click()
  await expect(page.getByTestId('navigation-pick-target')).toHaveCount(6)
  const targetBounds = await page.getByRole('button', { name: 'Navigate to Settings', exact: true }).boundingBox()
  await page.keyboard.down('Space')
  await page.mouse.move(targetBounds!.x + targetBounds!.width / 2, targetBounds!.y + targetBounds!.height / 2)
  await page.mouse.down()
  await page.mouse.move(targetBounds!.x + targetBounds!.width / 2 + 30, targetBounds!.y + targetBounds!.height / 2 + 25)
  await page.mouse.up()
  await page.keyboard.up('Space')
  await expect(page.getByTestId('navigation-pick-target')).toHaveCount(6)
  const canvas = await page.getByTestId('device-pane').boundingBox()
  await page.mouse.move(canvas!.x + canvas!.width / 2, canvas!.y + canvas!.height / 2)
  await page.keyboard.down('Control')
  await page.mouse.wheel(0, -160)
  await page.keyboard.up('Control')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('navigation-pick-target')).toHaveCount(0)
  await expect(phones(page)).toHaveCount(3)
  await expect(destination(page)).toHaveValue(original)
  const restoredBounds = await library.boundingBox()
  for (const key of ['x', 'y', 'width', 'height'] as const) expect(restoredBounds![key]).toBeCloseTo(originalBounds![key], 1)
  await page.getByRole('button', { name: 'Pick screen from canvas', exact: true }).click()
  await page.getByTestId('inspector-tab-preview').click()
  await expect(page.getByTestId('navigation-pick-target')).toHaveCount(0)
  await page.getByTestId('inspector-tab-settings').click()
  await expect(destination(page)).toHaveValue(original)
  await expect(page.getByTestId('logical-layers').locator('[aria-selected="true"]')).toContainText('Book row')
  await page.getByRole('button', { name: 'Pick screen from canvas', exact: true }).click()
  const settings = page.getByTestId('navigation-pick-target').filter({ hasText: 'Choose Settings' })
  await expect(settings).toHaveAttribute('aria-disabled', 'false')
  await settings.hover()
  await expect(page.getByTestId('logical-layers').locator('[aria-selected="true"]')).toContainText('Book row')
  const screenshot = testInfo.outputPath('navigation-screen-picker.png')
  await page.screenshot({ path: screenshot })
  await testInfo.attach('navigation screen picker', { path: screenshot, contentType: 'image/png' })
  await settings.click()
  await expect(page.getByTestId('navigation-pick-target')).toHaveCount(0)
  await expect(destination(page)).toHaveValue(/Settings/)
  await expect(page.getByTestId('navigation-destination-editor')).toContainText('Current: BookDetailView(book: book)')
  await page.getByRole('button', { name: 'Apply destination', exact: true }).click()
  await expect(page.getByTestId('navigation-destination-editor')).toContainText('Current: SettingsView()')
  await page.getByRole('button', { name: 'View source', exact: true }).click()
  const source = await page.getByTestId('editor').locator('.cm-content').innerText()
  expect(source).toContain('destination: SettingsView()')
  expect(source).toContain('BookRow(book: book)')
  expect(source).toContain('BookDetailView(book: book)')
  await page.getByTestId('workspace-design').click()
  await page.getByTestId('live-toggle').click()
  await page.getByTestId('render-tree').getByRole('button', { name: 'The Secret Garden, Frances Hodgson Burnett', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByRole('textbox', { name: 'Your name', exact: true })).toBeVisible()
})

test('picking a data-driven detail retains the selected row data rather than its preview sample', async ({ page }) => {
  await folio(page)
  await destination(page).fill('SettingsView')
  await destination(page).press('Escape')
  await page.getByRole('button', { name: 'Pick screen from canvas', exact: true }).click()
  const detail = page.getByTestId('navigation-pick-target').filter({ hasText: 'Choose Book details' })
  await expect(detail).toHaveAttribute('aria-disabled', 'false')
  await detail.click()
  await expect(destination(page)).toHaveValue(/Book detail/i)
  await expect(page.getByRole('button', { name: 'Apply destination', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'View source', exact: true }).click()
  await expect(page.getByTestId('editor').locator('.cm-content')).toContainText('NavigationLink(value: book)')
  await expect(page.getByTestId('editor').locator('.cm-content')).not.toContainText('destination: BookDetailView')
})
