import { expect, test } from '@playwright/test'
import { cards, expandCard } from './designer-helpers'

test('blank design starts in Edit and supports visible recovery without Code', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('gallery-source-design')).toHaveAttribute('aria-pressed', 'true')
  await page.getByTestId('template-blank').click()
  await page.getByTestId('template-confirm').click()
  await expect(page.getByTestId('template-gallery')).toBeHidden()
  // Edit is where Design starts: the one toolbar toggle offers Preview, not yet pressed.
  await expect(page.getByTestId('live-toggle')).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByTestId('design-undo')).toBeDisabled()
  // The settings panel is always beside the canvas, with no tab to find first.
  await expect(page.getByRole('complementary', { name: 'Settings', exact: true }).getByTestId('inspector-settings')).toBeVisible()
  await page.getByTestId('add-view').click()
  await page.getByTestId('add-view-text').click()
  const content = page.getByTestId('settings-basics').getByRole('textbox', { name: 'Text', exact: true })
  await content.fill('Campus Design Club')
  await content.press('Enter')
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toBeVisible()
  await page.getByTestId('design-undo').click()
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toHaveCount(0)
  await page.getByTestId('design-redo').click()
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toBeVisible()
  await page.getByTestId('reset-preview').click()
  await expect(page.getByTestId('design-feedback')).toHaveText('Preview reset. Your design is unchanged.')
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toBeVisible()
})

test('profile button labels and styles are editable and reset preserves the design', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('template-card').click()
  await page.getByTestId('template-confirm').click()
  await expect(page.getByTestId('template-gallery')).toBeHidden()
  // The button sits in the profile card, which a plain click selects whole; ⌘ reaches the button (D1).
  await page.getByTestId('render-tree').getByRole('button', { name: 'Follow', exact: true }).click({ modifiers: ['ControlOrMeta'] })
  const title = page.getByTestId('settings-basics').getByRole('textbox', { name: 'Title · otherwise', exact: true })
  await title.fill('Join club'); await title.press('Enter')
  const joined = page.getByTestId('settings-basics').getByRole('textbox', { name: /Title · when following is true/ })
  await joined.fill('Joined'); await joined.press('Enter')
  await expandCard(cards(page, 'buttonStyle'))
  await cards(page, 'buttonStyle').getByRole('combobox').selectOption('bordered')
  await page.getByTestId('live-toggle').click()
  await page.getByTestId('render-tree').getByRole('button', { name: 'Join club', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByText('Joined', { exact: true })).toBeVisible()
  await page.getByTestId('reset-preview').click()
  await expect(page.getByTestId('render-tree').getByText('Join club', { exact: true })).toBeVisible()
  await page.getByTestId('inspect-toggle').click()
  await page.getByTestId('render-tree').getByRole('button', { name: 'Join club', exact: true }).click({ modifiers: ['ControlOrMeta'] })
  await expect(title).toHaveValue('Join club')
  await expect(joined).toHaveValue('Joined')
  await expandCard(cards(page, 'buttonStyle'))
  await expect(cards(page, 'buttonStyle').getByRole('combobox')).toHaveValue('bordered')
})
