import { expect, test, type Page } from '@playwright/test'
import { cards, expandCard } from './designer-helpers'

async function start(page: Page) {
  await page.goto('/')
  await page.getByTestId('template-blank').click()
  await page.getByTestId('template-confirm').click()
  await expect(page.getByTestId('template-gallery')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Add screen', exact: true })).toBeEnabled()
}
async function add(page: Page, kind: string) {
  await expect(page.getByTestId('add-view')).toBeEnabled()
  await page.getByTestId('add-view').click()
  await page.getByTestId(`add-view-${kind}`).click()
  await expect(page.getByTestId('add-view-palette')).toBeHidden()
  await expect(page.getByTestId('authoring-inspector')).toHaveAttribute('aria-busy', 'false')
}
async function title(page: Page, name: string) {
  const field = page.getByTestId('settings-basics').getByRole('textbox', { name: 'Title', exact: true })
  await field.fill(name); await field.press('Enter')
  await expect(page.getByTestId('render-tree').getByRole('button', { name, exact: true })).toBeVisible()
}
async function screenAction(page: Page, screen: string, action: string) {
  await page.getByRole('button', { name: `Screen actions for ${screen}`, exact: true }).click()
  await page.getByRole('option', { name: action, exact: true }).click()
}
async function homeName(page: Page) {
  await screenAction(page, 'Main page', 'Rename')
  await page.getByRole('textbox', { name: 'Screen name', exact: true }).fill('Home')
  await page.getByRole('button', { name: 'Save screen name', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open screen Home', exact: true })).toBeEnabled()
}

test('screens create, rename, duplicate, reorder, remove and undo entirely in Design', async ({ page }) => {
  await start(page); await homeName(page)
  await page.getByRole('button', { name: 'Add screen', exact: true }).click()
  await page.getByRole('textbox', { name: 'Screen name', exact: true }).fill('Club details')
  await page.getByRole('combobox', { name: 'Screen layout', exact: true }).selectOption('HStack')
  await page.getByRole('button', { name: 'Create screen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open screen Club details', exact: true })).toBeEnabled()
  await page.getByTestId('render-tree').getByText('Club details', { exact: true }).dblclick()
  await page.getByRole('textbox', { name: 'Canvas text', exact: true }).fill('Campus Design Club')
  await page.getByRole('textbox', { name: 'Canvas text', exact: true }).press('Enter')
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toBeVisible()
  await screenAction(page, 'Club details', 'Duplicate')
  await expect(page.getByRole('button', { name: 'Open screen Club details copy', exact: true })).toBeEnabled()
  await screenAction(page, 'Club details copy', 'Move up')
  await expect(page.getByRole('region', { name: 'Screens', exact: true }).getByRole('button', { name: /^Open screen/ })).toHaveText(['HomeNavigation · App start', 'Club details copyRow · Standalone', 'Club detailsRow · Standalone'])
  await screenAction(page, 'Club details copy', 'Remove screen')
  await expect(page.getByRole('button', { name: 'Open screen Club details copy', exact: true })).toHaveCount(0)
  await page.getByTestId('design-undo').click()
  await expect(page.getByRole('button', { name: 'Open screen Club details copy', exact: true })).toBeEnabled()
  await expect(page.getByTestId('save-indicator')).toContainText('Saved locally')
  await page.reload()
  await page.getByRole('button', { name: 'Close welcome screen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open screen Club details', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Open screen Club details', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByText('Campus Design Club', { exact: true })).toBeVisible()
})

test('builds a three-screen club flow with custom color, image, navigation, sheet and independent value', async ({ page }) => {
  test.setTimeout(120_000)
  await start(page); await homeName(page)
  await add(page, 'text')
  const text = page.getByTestId('settings-basics').getByRole('textbox', { name: 'Text', exact: true })
  await text.fill('Campus Design Club'); await text.press('Enter')
  await page.getByRole('button', { name: 'Text color +', exact: true }).click()
  await expandCard(cards(page, 'foregroundColor'))
  await page.getByRole('textbox', { name: 'foregroundColor hex color', exact: true }).fill('#6D28D9')
  await page.getByRole('combobox', { name: 'foregroundColor color style', exact: true }).selectOption('__new')
  await page.getByRole('textbox', { name: 'Shared color name', exact: true }).fill('clubBrand')
  await page.getByRole('button', { name: 'Create and apply color', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'foregroundColor color style', exact: true })).toHaveValue('clubBrand')
  await page.getByTestId('project-resources').locator('summary').first().click()
  await page.getByLabel('Add bundled image', { exact: true }).setInputFiles('tests/fixtures/authoring-photo.png')
  await expect(page.getByTestId('project-resources').getByText(/authoring_photo|authoring-photo/).first()).toBeVisible()
  await add(page, 'image')
  await page.getByRole('combobox', { name: 'Bundled image', exact: true }).selectOption({ index: 1 })
  await expect(page.getByTestId('render-tree').locator('img')).toHaveCount(1)
  await add(page, 'button'); await title(page, 'Details')
  await page.getByRole('combobox', { name: 'On tap', exact: true }).selectOption('navigate')
  await page.getByRole('combobox', { name: 'Interaction screen', exact: true }).selectOption('__new')
  await page.getByRole('textbox', { name: 'Interaction screen name', exact: true }).fill('Club details')
  await page.getByRole('button', { name: 'Save interaction', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open screen Club details', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Open screen Home', exact: true }).click()
  await add(page, 'button'); await title(page, 'Join')
  await page.getByRole('combobox', { name: 'On tap', exact: true }).selectOption('sheet')
  await page.getByRole('combobox', { name: 'Interaction screen', exact: true }).selectOption('__new')
  await page.getByRole('textbox', { name: 'Interaction screen name', exact: true }).fill('Welcome')
  await page.getByRole('button', { name: 'Save interaction', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open screen Welcome', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Open screen Home', exact: true }).click()
  await add(page, 'button'); await title(page, 'Subscribe')
  await page.getByRole('combobox', { name: 'On tap', exact: true }).selectOption('toggle')
  await page.getByRole('combobox', { name: 'Interaction value', exact: true }).selectOption('__new')
  await page.getByRole('textbox', { name: 'Interaction value name', exact: true }).fill('subscribed')
  await page.getByRole('textbox', { name: 'Button label when on', exact: true }).fill('Subscribed')
  await page.getByRole('button', { name: 'Save interaction', exact: true }).click()
  await expect(page.getByTestId('settings-basics').getByRole('textbox', { name: /Title · when subscribed/ })).toHaveValue('Subscribed')
  await page.getByTestId('live-toggle').click()
  await expect(page.getByTestId('status-view')).toHaveAttribute('aria-busy', 'false')
  await page.getByTestId('render-tree').getByRole('button', { name: 'Subscribe', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByText('Subscribed', { exact: true })).toBeVisible()
  await page.getByTestId('render-tree').getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByText('Club details', { exact: true }).first()).toBeVisible()
  await page.getByTestId('reset-preview').click()
  await page.getByTestId('render-tree').getByRole('button', { name: 'Join', exact: true }).click()
  await expect(page.getByTestId('render-tree').getByText('Welcome', { exact: true }).first()).toBeVisible()
  await page.getByTestId('inspect-toggle').click()
  await expect(page.getByRole('region', { name: 'Screens', exact: true }).getByRole('button', { name: /^Open screen/ })).toHaveCount(3)
})

test('renames, duplicates and groups layers with a visible move destination and undo', async ({ page }) => {
  await start(page)
  await add(page, 'text')
  const tree = page.getByTestId('logical-layers')
  await tree.getByRole('button', { name: 'Actions for Text', exact: true }).click()
  await page.getByRole('option', { name: 'Rename layer…', exact: true }).click()
  await page.getByRole('textbox', { name: 'Layer name', exact: true }).fill('Club heading')
  await page.getByRole('button', { name: 'Save layer name', exact: true }).click()
  await tree.getByRole('button', { name: 'Actions for Club heading', exact: true }).click()
  await page.getByRole('option', { name: 'Duplicate', exact: true }).click()
  await expect(tree.locator('[data-source-name="Text"]')).toHaveCount(2)
  await tree.locator('[data-source-name="Text"]').first().click()
  await tree.locator('[data-source-name="Text"]').last().click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Group in Column', exact: true }).click()
  await expect(tree.locator('[data-source-name="VStack"]')).toHaveCount(2)
  await page.getByTestId('design-undo').click()
  await expect(tree.locator('[data-source-name="VStack"]')).toHaveCount(1)
  await expect(tree.locator('[data-source-name="Text"]')).toHaveCount(2)
  await tree.locator('[data-source-name="Text"]').last().click()
  await add(page, 'hstack')
  await tree.locator('[data-source-name="Text"]').first().click()
  await tree.getByRole('button', { name: 'Actions for Club heading', exact: true }).click()
  await page.getByRole('option', { name: 'Move into…', exact: true }).click()
  await page.getByRole('combobox', { name: 'Destination container', exact: true }).selectOption({ label: 'Row · container 1' })
  await page.getByRole('button', { name: 'Move layers', exact: true }).click()
  await expect(page.getByTestId('design-feedback')).toHaveText('Design updated.')
  await expect(page.getByRole('alert')).not.toContainText('cannot')
  await tree.getByRole('button', { name: 'Collapse all layers', exact: true }).click()
  await tree.getByRole('button', { name: 'Expand all layers', exact: true }).click()
  await expect(tree.getByRole('treeitem', { name: 'Club heading, Text', exact: true })).toHaveAttribute('aria-level', '3')
})
