import { expect, test } from '@playwright/test'

test('Design opens first with an interactive preview and settings', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('gallery-dismiss').click()
  await expect(page.getByTestId('workspace')).toHaveAttribute('data-mode', 'design')
  await expect(page.getByTestId('editor')).toBeHidden()
  await expect(page.getByTestId('device-select')).toBeVisible()
  await expect(page.getByTestId('render-tree')).toBeVisible()
  await expect(page.getByTestId('workspace-design')).toHaveAttribute('aria-pressed', 'true')
  await page.getByTestId('workspace-develop').click()
  await expect(page.getByTestId('editor')).toBeVisible()
  await expect(page.getByTestId('render-tree')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Workspace view' }).getByRole('button')).toHaveCount(2)
  await page.getByTestId('workspace-design').click()
  await expect(page.getByTestId('render-tree')).toBeVisible()
  await expect(page.getByTestId('editor')).toBeHidden()
})

test('opening a source file from Design reveals code and preserves the preference', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('gallery-dismiss').click()
  await page.getByTestId('navigator-tab-project').click()
  await page.getByTestId('file-rail').getByText('CounterApp.swift', { exact: true }).click()
  await expect(page.getByTestId('workspace')).toHaveAttribute('data-mode', 'develop')
  await expect(page.getByTestId('editor')).toBeVisible()
  await page.reload()
  await page.getByTestId('gallery-dismiss').click()
  await expect(page.getByTestId('workspace')).toHaveAttribute('data-mode', 'develop')
})

test('Design keeps preview settings reachable in a small window', async ({ page }) => {
  await page.setViewportSize({ width: 760, height: 700 })
  await page.goto('/')
  await page.getByTestId('gallery-dismiss').click()
  await expect(page.getByTestId('file-rail')).toBeHidden()
  await expect(page.getByTestId('device-select')).toBeVisible()
  await expect(page.getByTestId('zoom-select')).toBeVisible()
  await page.getByTestId('scheme-toggle').getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(page.getByTestId('scheme-toggle').getByRole('button', { name: 'Dark', exact: true })).toHaveAttribute('aria-pressed', 'true')
})


test('workspace theme persists independently of preview appearance and mode', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('gallery-dismiss').click()
  const theme = page.getByTestId('workspace-theme')
  const previewLight = page.getByTestId('scheme-toggle').getByRole('button', { name: 'Light', exact: true })
  await previewLight.click()
  await theme.click()
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'dark')
  await expect(previewLight).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('render-tree')).toHaveCSS('color-scheme', 'light')
  await expect(page.getByTestId('toolbar')).toHaveCSS('background-color', 'rgb(36, 36, 38)')
  await page.getByTestId('workspace-develop').click()
  await expect(page.getByTestId('editor').locator('.cm-editor')).toHaveCSS('background-color', 'rgb(32, 32, 34)')
  await page.reload()
  await page.getByTestId('gallery-dismiss').click()
  await expect(theme).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('workspace')).toHaveAttribute('data-mode', 'develop')
  await expect(previewLight).toHaveAttribute('aria-pressed', 'true')
  await theme.click()
  await expect(page.getByTestId('editor').locator('.cm-editor')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'light')
})
